name: Deploy container
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Make test script executable
        run: chmod +x test_dyndns.sh
        
      - name: Run test suite
        run: ./test_dyndns.sh

  deploy:
    name: Deploy container
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build image
        run: docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/digitalocean-dyndns:${{ github.sha }} .
      - name: tag and push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/digitalocean-dyndns:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/digitalocean-dyndns:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/digitalocean-dyndns:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/digitalocean-dyndns:latest