name: Test Suite

on:
  push:
    branches:
      - main
      - copilot/*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Make test script executable
        run: chmod +x test_dyndns.sh
        
      - name: Run test suite
        run: ./test_dyndns.sh
        
      - name: Test script validation
        run: |
          echo "Test script completed"
          if [ $? -eq 0 ]; then
            echo "✅ All tests passed!"
          else
            echo "❌ Tests failed!"
            exit 1
          fi